apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos-service
  namespace: loja-veloz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamentos-service
  template:
    metadata:
      labels:
        app: pagamentos-service
    spec:
      containers:
        - name: pagamentos-service
          image: pagamentos-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: loja-veloz-config
            - secretRef:
                name: loja-veloz-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: pagamentos-service
  namespace: loja-veloz
spec:
  selector:
    app: pagamentos-service
  ports:
    - port: 3002
      targetPort: 3002
